presets/lara/tooltip/index.js

This is for #5. It fixes the incorrect Tailwind classes.

fix #5: use correct Tailwind classes in Tooltip

---

presets/lara/button/index.js

loading button style is missing from `lara/button/index.js`.

style: loading button

---

presets/lara/inputnumber/index.js
presets/wind/inputnumber/index.js

Fixes InputNumber component issue when using w-full class.
Before
After

Fix inputNumber display

---

presets/lara/splitbutton/index.js

Closes Lara SplitButton Small Font Size #82

Fix SplitButton small font size

---

components/app/AppConfig.vue
components/doc/codeeditor/templates.js

In presets and labeling already using `Lara`, but the theme switcher still uses `PrimeOne`

Change PrimeOne to Lara for consistency

---

presets/lara/calendar/index.js
presets/wind/calendar/index.js

After I added the `showSeconds` prop in `Calendar`, I found the seconds' section is un-styled.

fix: add second picker in calendar

---

presets/lara/dialog/index.js
presets/lara/fieldset/index.js

Minor:   
In the Lara presets, a couple of files have duplicate TailwindCSS properties
- Dialog
- Fieldset

Lara - remove duplicate tailwind class properties

---

doc/datatable/RowExpansionDoc.vue

This PR fixed `Expand All` on DataTable - Row Expansion [here](https://tailwind.primevue.org/datatable/#row_expansion).

Fix expand all not working on DataTable - Row Expansion

---

presets/lara/inputnumber/index.js

On button focus the outline is not fully visible
I added z-10 to input on focus which fixed the problem
I'm not sure about other inputs, I'll try to notify you when I find something else.

Lara - fix InputNumber focus outline

---

presets/lara/inputnumber/index.js
presets/lara/inputtext/index.js

Similar to #94 - these two components need the same z-index treatment
Seen in combo with InputGroup and when a component positioned on the right side.
ex: InputText from site:

fix: Lara - "focus:z-10" apply to both InputText/InputNumber

---

doc/contextmenu/BasicDoc.vue
presets/lara/contextmenu/index.js
presets/wind/contextmenu/index.js

Hey there 👋 
I've realized the styles were missing for disabled contextmenu items, so I've added them in this PR. I've also added an example in the docs.
Lara:
Wind:

fix(contextmenu): add missing disabled styles

---

presets/lara/avatar/index.js
presets/wind/avatar/index.js

I have found and fixed what I believe to be an issue with the "Avatar" component on both presets that has been bothering me for a while.
The image from the component doesn't update with the "shape" prop like the root container does:
`<Avatar
image="avatar.png"
size="xlarge"
shape="circle"
:pt="{root: 'p2 bg-red-200!'}"
:pt-options="{ mergeProps: true }"
/>` *
\* Obs.: Padding and red background added to the root element, as an example, to exaggerate the discrepancy with the image.
It seems that the images used in the docs are, conveniently enough, rounded PNGs with transparent backgrounds, hiding this issue. Unless it's by design, but that doesn't seem likely when comparing this behavior with the "Lara" theme in styled-mode, using vanilla CSS.
This is my first time contributing, so, let …

fix(avatar): add missing classes related to the shape prop for the image

---

presets/lara/inputnumber/index.js
presets/lara/inputtext/index.js
presets/lara/password/index.js
presets/wind/autocomplete/index.js
presets/wind/calendar/index.js
presets/wind/inputtext/index.js
presets/wind/paginator/index.js
presets/wind/password/index.js
presets/wind/splitbutton/index.js
presets/wind/tabmenu/index.js
presets/wind/tabview/index.js

Since `px` is a valid spacing value in the [default tailwind config](https://github.com/tailwindlabs/tailwindcss/blob/master/stubs/config.full.js#L842), it is not necessary to use value interpolation to get 1px for padding, margin, etc.

refactor: use px utilities from the default tailwind config

---

presets/lara/toast/index.js
presets/wind/toast/index.js

Hi
If we use the `toast` component without the summary field. The styles are not correct
Updated presets (Lara, Wind) to show it correctly. Centered the content vertically if the summary is not there and removed margin-top from the detail.
Fix demo: https://stackblitz.com/edit/icxzv3?file=src%2FApp.vue,src%2Fpresets%2Fwind%2Ftoast%2Findex.js,src%2Fpresets%2Flara%2Ftoast%2Findex.js,src%2Fmain.js

fix toast styling when summary prop is not added

---

presets/lara/timeline/index.js
presets/wind/timeline/index.js

`context.index === context.count` always return false cause `context.index` start from 0

fix timeline last content preset not applying

---

presets/lara/datatable/index.js

Empty table look odd with the other default components/dragging and dropping rows (when the background is visible). I added default background to table body.
before:
after:

add default background to table body in datatable

---

presets/lara/datatable/index.js

in dark mode, when you use scrollable attribute on datatable and sort column, the style of the header seems to be broken
before:
after:

fix datatable with scrollable attribute breaks the sortable header style

---

presets/lara/datatable/index.js

When you add, for example, a button to datatable column, then freeze column, the column would display under the column. 
before:
after:
Frozen rows might need this fix too.

fix z-index in datatable when column is frozen

---

presets/wind/tabview/index.js

The code contained duplicate lines at Line 108 and 111, and the order was incorrect. I have reorganized the declarations and corrected the duplication issue. Additionally, I replaced dark:bg-surface-800 with dark:bg-primary-400 to fix Dark Mode.

Fix TabView Duplicate

---

presets/aura/inputtext/index.js
presets/lara/inputtext/index.js

This fixes the FloatLabel state for the below components
- Password
- AutoComplete
- InputMask
- InputNumber
- Textarea

Fix FloatLabel filled state for several components

---

presets/aura/floatlabel/index.js
presets/lara/floatlabel/index.js

Multiple input components (`AutoComplete`, `CascadeSelect`, `DatePicker`, `InputMask`, `InputNumber`, `InputText`, `MultiSelect`, `TextArea` etc) set a `z-10` class, either by default or on focus. 
Setting the same `z-index` prevents the Floatlabel from transition from behind the input on focus.

Fix FloatLabel z-index

---

presets/lara/tooltip/index.js

Shadow should be on "text" section and not on root which includes the arrow

fix: Lara Tooltip shadow 
